export const worksHeaderMap: Record<string, string> = {
    'Код': 'code',
    'Наименование': 'name',
    'Ед. изм.': 'unit',
    'Ед.изм.': 'unit',
    'Базовая цена': 'price',
    'Цена': 'price',
    'Этап': 'phase',
    'Этап№': 'phase',
    'Этап №': 'phase',
    'Этап № ': 'phase',
    'этап': 'phase',
    'фаза': 'phase',
    'Раздел': 'category',
    'Подраздел': 'subcategory',
    'Краткое описание': 'shortDescription',
    'Описание': 'description',
    'code': 'code',
    'name': 'name',
    'unit': 'unit',
    'price': 'price',
    'phase': 'phase',
    'category': 'category',
    'subcategory': 'subcategory',
};

export const worksRequiredFields = ['code', 'name', 'unit', 'price'];

export const materialsHeaderMap: Record<string, string> = {
    'Код': 'code',
    'Наименование': 'name',
    'Ед изм': 'unit',
    'Ед. изм.': 'unit',
    'Ед.изм.': 'unit',
    'Базовая цена': 'price',
    'Цена': 'price',
    'Поставщик': 'vendor',
    'Вес (кг)': 'weight',
    'Категория LV1': 'categoryLv1',
    'Категория LV2': 'categoryLv2',
    'Категория LV3': 'categoryLv3',
    'Категория LV4': 'categoryLv4',
    'URL товара': 'productUrl',
    'URL изображения': 'imageUrl',
    'Раздел': 'category',
    'Подраздел': 'subcategory',
    'Краткое описание': 'shortDescription',
    'Описание': 'description',
    'code': 'code',
    'name': 'name',
    'unit': 'unit',
    'price': 'price',
    'vendor': 'vendor',
    'weight': 'weight',
    'categoryLv1': 'categoryLv1',
    'categoryLv2': 'categoryLv2',
    'categoryLv3': 'categoryLv3',
    'categoryLv4': 'categoryLv4',
    'productUrl': 'productUrl',
    'imageUrl': 'imageUrl',
};

export const materialsRequiredFields = ['code', 'name', 'unit', 'price'];
